name: Scrape NEU Gym Occupancy

on:
  push:  # Trigger on push
    branches:
      - main 

  schedule:
    # Monday (5:30 AM - midnight)
    - cron: '0 6-23 * * 1'    # Every hour from 6 AM to 11 PM
    - cron: '30 5 * * 1'      # 5:30 AM run
    
    # Tuesday (5:30 AM - midnight)
    - cron: '0 6-23 * * 2'    # Every hour from 6 AM to 11 PM
    - cron: '30 5 * * 2'      # 5:30 AM run
    
    # Wednesday (5:30 AM - midnight)
    - cron: '0 6-23 * * 3'    # Every hour from 6 AM to 11 PM
    - cron: '30 5 * * 3'      # 5:30 AM run
    
    # Thursday (5:30 AM - midnight)
    - cron: '0 6-23 * * 4'    # Every hour from 6 AM to 11 PM
    - cron: '30 5 * * 4'      # 5:30 AM run
    
    # Friday (5:30 AM - 9 PM)
    - cron: '0 6-20 * * 5'    # Every hour from 6 AM to 8 PM
    - cron: '30 5 * * 5'      # 5:30 AM run
    
    # Saturday (8 AM - 9 PM)
    - cron: '0 8-20 * * 6'    # Every hour from 8 AM to 8 PM
    
    # Sunday (8 AM - midnight & 10 AM - midnight)
    - cron: '0 8-23 * * 0'    # Every hour from 8 AM to 11 PM
  
  workflow_dispatch:  # Allows manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager gitpython
    
    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: Run scraper
      run: python scraper.py
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: ${{ github.ref }}
