name: Scrape NEU Gym Occupancy

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 6-23 * * 1-5'  # Monday to Friday: Every hour from 6 AM to 11 PM
    - cron: '0 8-20 * * 6'  # Saturday: Every hour from 8 AM to 8 PM
    - cron: '0 8-23 * * 0'  # Sunday: Every hour from 8 AM to 11 PM

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager gitpython pdfplumber pyppeteer

    - name: Run scraper
      run: python scraper.py

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
