name: Scrape NEU Gym data

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 11-23 * * 1-5'
    - cron: '0 0-4 * * 2-6'

    - cron: '0 13-23 * * 6'
    - cron: '0 0-1 * * 0'

    - cron: '0 13-23 * * 0'
    - cron: '0 0-4 * * 1'

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run scraper and visualizer
        run: |
          python scraper.py
          python visual.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'RepsAndCommits'
          git config --global user.email 'RepsAndCommits@github.com'
          git add plots/gym_occupancy_analysis.png
          git add data/facility_data.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m 'Update facility data' && git push)
