name: Scrape NEU Gym Occupancy

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 11-23 * * 1-5'
    - cron: '0 0-4 * * 2-6'

    - cron: '0 13-23 * * 6'
    - cron: '0 0-1 * * 0'

    - cron: '0 13-23 * * 0'
    - cron: '0 0-4 * * 1'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run scraper
      run: python scraper.py

    - name: Commit CSV changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/gym_occupancy.csv
        git commit -m "Update gym occupancy CSV"
        git push