name: Scrape NEU Gym Occupancy

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 11-23 * * 1-5'
    - cron: '0 0-4 * * 2-6'

    - cron: '0 13-23 * * 6'
    - cron: '0 0-1 * * 0'

    - cron: '0 13-23 * * 0'
    - cron: '0 0-4 * * 1'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager gitpython pdfplumber pyppeteer

    - name: Run scraper
      run: python scraper.py

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: main