name: Scrape NEU Gym Occupancy

on:
  push:  # Trigger on push
    branches:
      - main 

  schedule:
    # Monday (5:30 AM - midnight)
    - cron: '0 6-23 * * 1'    # Every hour from 6 AM to 11 PM
    - cron: '30 5 * * 1'      # 5:30 AM run
    
    # Tuesday (5:30 AM - midnight)
    - cron: '0 6-23 * * 2'    # Every hour from 6 AM to 11 PM
    - cron: '30 5 * * 2'      # 5:30 AM run
    
    # Wednesday (5:30 AM - midnight)
    - cron: '0 6-23 * * 3'    # Every hour from 6 AM to 11 PM
    - cron: '30 5 * * 3'      # 5:30 AM run
    
    # Thursday (5:30 AM - midnight)
    - cron: '0 6-23 * * 4'    # Every hour from 6 AM to 11 PM
    - cron: '30 5 * * 4'      # 5:30 AM run
    
    # Friday (5:30 AM - 9 PM)
    - cron: '0 6-20 * * 5'    # Every hour from 6 AM to 8 PM
    - cron: '30 5 * * 5'      # 5:30 AM run
    
    # Saturday (8 AM - 9 PM)
    - cron: '0 8-20 * * 6'    # Every hour from 8 AM to 8 PM
    
    # Sunday (8 AM - midnight & 10 AM - midnight)
    - cron: '0 8-23 * * 0'    # Every hour from 8 AM to 11 PM
  
  workflow_dispatch:  # Allows manual triggers

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      run: |
        wget -q -O /tmp/chrome.deb http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_109.0.5414.74-1_amd64.deb
        sudo apt install -y /tmp/chrome.deb 
        rm /tmp/chrome.deb
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager gitpython
    
    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: Run scraper
      run: python scraper.py
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: ${{ github.ref }}
